### ISSUE TITLE
Добавить в readme текст из коммента

### ISSUE THREAD

**Issue by ElenaAgapitova** [ElenaAgapitova/hw_git#1]
### Семинар №3

Данное домашнее задание является продолжением домашнего задания, которое вы выполняли на предыдущем семинаре в репозитории с 
собственным проектом.

В этом задании предлагаем каждому из вас побыть в роли тимлида.

1. Пригласите в свой проект кого-то из коллег по обучению, дайте им доступ к своему репозиторию (кроме ветки master).

2. Поставьте ему в GitHub задачу по своему проекту, попросите её выполнить в отдельной ветке, а после выполнения — 
создать pull request и перевести задачу обратно на вас.

3. Проверьте выполнение задачи, примите pull request и удалите ветку, в которой решалась данная задача.

**Comment by artem-maklashev** [comment]
in work

**Comment by artem-maklashev** [comment]
Done https://github.com/ElenaAgapitova/hw_git/pull/2

**Comment by artem-maklashev** [comment]
Done https://github.com/ElenaAgapitova/hw_git/pull/3

**Comment by artem-maklashev** [comment]
Во пробуй https://github.com/ElenaAgapitova/hw_git/pull/4
